//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nForums.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class POST
    {
        public POST()
        {
            this.COMMENTs = new HashSet<COMMENT>();
            this.LIKE_POST = new HashSet<LIKE_POST>();
            this.REPORT_POST = new HashSet<REPORT_POST>();
        }
    
        public int ID { get; set; }
        public string SUBJECT { get; set; }
        public string CONTEN { get; set; }
        public Nullable<System.DateTime> CREATED { get; set; }
        public Nullable<int> THREAD_ID { get; set; }
        public Nullable<int> USER_ID { get; set; }
        public Nullable<int> STATUS { get; set; }
    
        public virtual THREAD THREAD { get; set; }
        public virtual USER USER { get; set; }
        public virtual ICollection<COMMENT> COMMENTs { get; set; }
        public virtual ICollection<LIKE_POST> LIKE_POST { get; set; }
        public virtual ICollection<REPORT_POST> REPORT_POST { get; set; }
    }
}
