//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nForums.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPORT_POST
    {
        public int ID { get; set; }
        public Nullable<int> POST_ID { get; set; }
        public Nullable<int> USER_ID { get; set; }
        public string REASON_REPORT { get; set; }
        public Nullable<System.DateTime> CREATED { get; set; }
    
        public virtual POST POST { get; set; }
        public virtual USER USER { get; set; }
    }
}
