//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nForums.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        public USER()
        {
            this.POSTs = new HashSet<POST>();
            this.THREADs = new HashSet<THREAD>();
            this.COMMENTs = new HashSet<COMMENT>();
            this.REPLY_COMMENT = new HashSet<REPLY_COMMENT>();
            this.LIKE_POST = new HashSet<LIKE_POST>();
            this.REPORT_POST = new HashSet<REPORT_POST>();
        }
    
        public int ID { get; set; }
        public string USERNAME { get; set; }
        public string PASSWORD { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> CREATED { get; set; }
        public Nullable<byte> IS_MODERATOR { get; set; }
        public Nullable<int> STATUS { get; set; }
        public Nullable<byte> GENDER { get; set; }
    
        public virtual ICollection<POST> POSTs { get; set; }
        public virtual ICollection<THREAD> THREADs { get; set; }
        public virtual ICollection<COMMENT> COMMENTs { get; set; }
        public virtual ICollection<REPLY_COMMENT> REPLY_COMMENT { get; set; }
        public virtual ICollection<LIKE_POST> LIKE_POST { get; set; }
        public virtual ICollection<REPORT_POST> REPORT_POST { get; set; }
    }
}
